// const promise = new Promise((resolve, reject) => {
//     console.log('async task execution')
//     if (0) {
//         const person={
//             name:'sumit'
//         }
//         resolve(person)
//     } else {
//         const error={
//             errCode:'404 err'
//         }
//         reject(error)
//     }
// });

// promise.then(
//     (val) => {
//         console.log(val)
//     }, (err) => {
//       console.log(err)
//     }
//     )
//     .catch(()=>console.log('failed'))
//     .finally(()=>{
//         console.log('clean up')
//     });

